In [24]:
import numpy as np

In [25]:
my_list = [1,2,3,4,5]
my_tup = (2, 3, 4, 7, 5)
arr = np.array(my_list)
arr2 = np.array(my_tup)

In [26]:
print(type(my_list))
print(my_list)
print(type(arr))
print(arr)
print(type(my_tup))
print(my_tup)
print(type(arr2))
print(arr2)


<class 'list'>
[1, 2, 3, 4, 5]
<class 'numpy.ndarray'>
[1 2 3 4 5]
<class 'tuple'>
(2, 3, 4, 7, 5)
<class 'numpy.ndarray'>
[2 3 4 7 5]


# 0D arrays 

### .ndim method --> checks how many dimensions the arrays have:

In [27]:
arr = np.array(34)
print(arr)
print(arr.ndim)

34
0


# 1D arrays

In [28]:
arr = np.array([20,34,534])
print(arr)
print(arr.ndim)

[ 20  34 534]
1


# 2D arrays

In [33]:
arr = np.array([[20, 32, 54], [543, 53, 2]])
print(arr)
print(arr.ndim)

[[ 20  32  54]
 [543  53   2]]
2


# 3D arrays

In [30]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr)
print(arr.ndim)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
3


# Custom array dimensions


##### In this array, the innermost dimension (5th dim) has 4 elements, the 4th dim has 1 element that is the vector, the 3rd dim has 1 element that is the matrix with the vector, the 2nd dim has 1 element that is 3D array and 1st dim has 1 element that is a 4D array.

In [31]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5
