In [6]:
from numpy import random
import numpy as np

In [3]:
a = random.choice([2,3], p=[0.3,0.7], size=10)
print(a)

[3 2 3 2 3 3 3 3 3 3]


### Same example as above, but return a 2-D array with 3 rows, each containing 5 values.

In [5]:
a = random.choice([2,4,6], p=[0.3,0.3,0.4], size=(3,10))
print(a)

[[2 2 4 2 6 4 4 6 6 2]
 [4 2 2 2 6 4 4 6 6 6]
 [2 2 6 6 4 6 2 6 6 2]]


# Random permutation

##### The shuffle() method makes changes to the original array.

In [9]:
arr = np.array([1,2,3,4,5])
random.shuffle(arr)
print(arr)

[5 4 1 3 2]


##### The permutation() method returns a re-arranged array (and leaves the original array un-changed).

In [19]:
arr = np.array([1,2,3,4,5])
a = random.permutation(arr)
print(f'arr: {arr}\na: {a}')

arr: [1 2 3 4 5]
a: [2 3 1 5 4]
