In [1]:
from numpy import random

# Generate Random Number

In [2]:
a = random.randint(100)
print(a)

68


### The randint() method takes a size parameter where you can specify the shape of an array.

In [7]:
a = random.randint(100, size=5)
print(a)

[65 34 60 47 23]


##### Generate a 2-D array with 3 rows, each row containing 5 random integers from 0 to 100:

In [10]:
a = random.randint(100, size=(3, 5))
print(a)

[[33 25 28 13  7]
 [43 78  5 33 50]
 [53 62 54 78 40]]


# Random between 0 and 1

In [6]:
a = random.rand()
print(a)

0.4247562774769602


### The rand() method also allows you to specify the shape of the array.

In [11]:
a = random.rand(3)
print(a)

[0.80577382 0.94177961 0.24790175]


In [13]:
a = random.rand(2,4)
print(a)

[[0.88757613 0.01448624 0.67144112 0.71137351]
 [0.03379466 0.95224592 0.44452501 0.03046974]]


# Generate Random Number From Array

#### The choice() method takes an array as a parameter and randomly returns one of the values.

In [16]:
a = random.choice([2,3,4,5,6,7,8,9])
print(a)

5


#### Add a size parameter to specify the shape of the array.

In [18]:
a = random.choice([2,3,4,5,6,7,8,9], size=(2, 3))
print(a)

[[9 9 5]
 [2 5 6]]
